incluído assemble

diff --git a/bluebank-spa-angular/.s2i/bin/assemble b/bluebank-spa-angular/.s2i/bin/assemble
--- a/bluebank-spa-angular/.s2i/bin/assemble
+++ b/bluebank-spa-angular/.s2i/bin/assemble
@@ -1,10 +1,15 @@
 #!/bin/sh
-echo "Making pre-invocation changes..."
 
+echo "Making pre-invocation changes..."
+/usr/libexec/s2i/assemble
+rc=$?
+if [ $rc -eq 0 ]; then
  echo "Making post-invocation changes..." 
  echo '###### npm install -g angular-cli'
  npm install -g @angular/cli@1.2.5
+ npm install -g @angular/compiler-cli@2.3.1
  echo '###### npm install -g angular-cli end'
- /usr/libexec/s2i/assemble
-
- #echo "#####: assemble !"
+else
+ echo "Error: assemble failed!"
+fi
+exit $rc
